---
- name: Playbook for customize Debian9 by CIS
  hosts: all
  become: yes

  tasks: 

  - name: Copy config file for unneeded filesystems (1.1.1.1-1.1.1.5)
    copy: 
      src: ./unneededfilesystem.conf
      dest: /etc/modprobe.d/ 
      mode: 777

  - name: Ensure mounting of unneeded filesystems (1.1.1.1-1.1.1.5)
    command: rmmod unneededfilesystem

  - name: Remove freevxfs module (1.1.1.1)
    modprobe: 
      name: freevxfs
      state: absent

  - name: Remove jffs2 module (1.1.1.2)
    modprobe: 
      name: jffs2
      state: absent

  - name: Remove hfs module (1.1.1.3)
    modprobe: 
      name: hfs
      state: absent

  - name: Remove hfsplus module (1.1.1.4)
    modprobe: 
      name: hfsplus
      state: absent
      
  - name: Remove udf module (1.1.1.5)
    modprobe: 
      name: udf
      state: absent    
  
  - name: Ensure /tmp is configurated (1.1.2, 1.1.6)
    shell: mount | grep /tmp

  - name: nodev,nosuid,noexec option for /tmp (1.1.3-1.1.5)
    lineinfile:
      dest: /etc/fstab
      regexp: '/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-tmp /tmp ext4 nodev,nosuid,noexec 0 2'

  - name: Ensure separate partition exist for /var/tmp (1.1.7)
    shell: mount | grep /var/tmp  
      
  - name: nodev,nosuid,noexec option for /var/tmp (1.1.8-1.1.10)
    lineinfile:
      dest: /etc/fstab
      regexp: '/var/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-var/tmp /var/tmp ext4 nodev,nosuid,noexec 0 2'  
 
  - name: Ensure separate partition exist for /var/log (1.1.11)
    shell: mount | grep /var/log 

  - name: Ensure separate partition exist for /var/log/audit (1.1.12)
    shell: mount | grep /var/log/audit  

  - name: Ensure separate partition exist for /home (1.1.13)
    shell: mount | grep /home      

  - name: nodev option for /home (1.1.14)
    lineinfile:
      dest: /etc/fstab
      regexp: '/home'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-home /home ext4 nodev 0 2'

  - name: nodev,nosuid,noexec option for /dev/shm (1.1.15-1.1.17)
    lineinfile:
      dest: /etc/fstab
      regexp: '/dev/shm'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-dev/shm /dev/shm ext4 nodev,nosuid,noexec 0 2'

  - name: sticky bit for /var (1.1.21)
    shell: chmod -R +t /var

  - name: sticky bit for /home (1.1.21)
    shell: chmod -R +t /home

  - name: sticky bit for /tmp (1.1.21)
    shell: chmod -R +t /tmp

  - name: noauto option for cd/dvd (1.1.22)
    lineinfile:
      dest: /etc/fstab
      regexp: '/cdrom0'
      insertbefore: 'defaults'
      line: '/dev/sr0 /media/cdrom0 udf,iso9660 user,noauto 0 0'

 # - name: install aide (1.3.1)
 #   apt: 
 #     name: aide

 # - name: create regulary checking filesystem job (1.3.2)
 #   cron:
 #     name: 'regulary checking filesystem'
 #     minute: '0'
 #     hour: '5'
 #     job: /usr/bin/aide.wrapper 

  - name: confin premitions bootloader prt.1 (1.4.1)
    shell: chown root:root /boot/grub/grub.cfg   

  - name: confin premitions bootloader prt.2 (1.4.1)
    shell: chmod og-rwx /boot/grub/grub.cfg     

  - name: checking bootloader password (1.4.2)
    shell: passwd -S  

  - name: checking root password (1.4.3)
    shell: passwd root     

  - name: added line in limits.conf (1.5.1)
      lineinfile: dest: '/etc/security/limits.conf'
      regexp: ''
      insertbefore: EOF
      line: '* hard core 0'

  - name: set parameter in sysctl.conf (1.5.1)
      lineinfile: dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'fs.suid_dumpable = 0'     

  - name: run command to the activate kernel parameter (1.5.1)
    shell: sysctl -w fs.suid_dumpable=0

  - name: set parameter in sysctl.conf (1.5.2)
      lineinfile: dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'kernel.randomize_va_space = 2'     

  - name: run command to the activate kernel parameter (1.5.2)
    shell: sysctl -w kernel.randomize_va_space=2

  - name: restore binaries (1.5.4)
    shell: prelink -ua

  - name: remove prelink (1.5.4)
    apt:
      name: prelink
      state: absent

  - name: checking /etc/motd file (1.7.1.1)
    shell: cat /etc/motd

  - name: configuration local login banner (1.7.1.2)
    lineinfile:
      dest: /etc/issue
      regexp: '*Debian*'
      insertbefore: BOF
      line: 'Authorized uses only. All activity may be monitored and reported.'

  - name: configuration remote login banner (1.7.1.3)
    lineinfile:
      dest: /etc/issue.net
      regexp: '*Debian*'
      insertbefore: BOF
      line: 'Authorized uses only. All activity may be monitored and reported.'

  - name: change ownership for /etc/motd (1.7.1.4)
    shell: chown root:root /etc/motd

  - name: change premissions for /etc/motd (1.7.1.4)
    shell: chmod 644 /etc/motd

  - name: change ownership for /etc/issue (1.7.1.5)
    shell: chown root:root /etc/issue

  - name: change premissions for /etc/issue (1.7.1.5)
    shell: chmod 644 /etc/issue

  - name: change ownership for /etc/issue.net (1.7.1.6)
    shell: chown root:root /etc/issue.net

  - name: change premissions for /etc/issue.net (1.7.1.6)
    shell: chmod 644 /etc/issue.net

  - name: edit greeter.dconf-defaults (1.7.2)
    lineinfile:
      dest: /etc/gdm3/greeter.dconf-defaults
      regexp: 'banner-message'
      insertbefore: BOF
      line: 'banner-message-enable=true'

  - name: edit greeter.dconf-defaults prt.2 (1.7.2)
    lineinfile:
      dest: /etc/gdm3/greeter.dconf-defaults
      regexp: ''
      insertbefore: EOF
      line: 'Authorized uses only. All activity may be monitored and reported.'
    tags: 
      - section_1  

  - name: remove xinetd (2.1.1)
    apt:
      name: xinetd
      state: absent 
      purge: yes
    tags: 
      - section_2  

  - name: remove xinetd (2.1.2)
    apt:
      name: openbsd-inetd
      state: absent
    tags: 
      - section_2  

  - name: remove xserver-xorg* (2.2.2)
    apt:
      name: xserver-xorg*
      state: absent
    tags: 
      - section_2    
  
  - name: disabled avahi-daemon (2.2.3)     
    shell: systemctl disable avahi-daemon
    tags: 
      - section_2                      

  - name: disabled cups (2.2.4)     
    shell: systemctl disable cups
    tags: 
      - section_2

  - name: disabled DHCP (2.2.5)     
    shell: systemctl disable isc-dhcp-server
    tags: 
      - section_2

  - name: disabled DHCP (v6) (2.2.5)     
    shell: systemctl disable isc-dhcp-server6
    tags: 
      - section_2        

  - name: disabled ldap (2.2.6)     
    shell: systemctl disable slapd 
    tags: 
      - section_2 

  - name: disabled nfs (2.2.7)     
    shell: systemctl disable nfs-server
    tags: 
      - section_2

  - name: disabled rpc (2.2.7)     
    shell: systemctl disable rpcbind
    tags: 
      - section_2

  - name: disabled dns server (2.2.8)     
    shell: systemctl disable bind9
    tags: 
      - section_2

  - name: disabled ftp server (2.2.9)     
    shell: systemctl disable vsftpd
    tags: 
      - section_2

  - name: disabled http server (2.2.10)     
    shell: systemctl disable apache2
    tags: 
      - section_2

  - name: remove exim4 (2.2.11)
    apt:
      name: exim4
      state: absent
      purge: yes
    tags: 
      - section_2  

  - name: disabled samba (2.2.12)     
    shell: systemctl disable smbd
    tags: 
      - section_2

  - name: disabled http proxy server (2.2.13)     
    shell: systemctl disable squid
    tags: 
      - section_2

  - name: disabled snmp server (2.2.14)     
    shell: systemctl disable snmpd
    tags: 
      - section_2

  - name: disabled rsync (2.2.16)     
    shell: systemctl disable rsync
    tags: 
      - section_2 

  - name: disabled NIS (2.2.17)     
    shell: systemctl disable nis
    tags: 
      - section_2  

  - name: remove NIS client (2.3.1)
    apt:
      name: ypbind
      state: absent
    tags: 
      - section_2   

  - name: remove rsh client (2.3.2)
    apt:
      name: rsh
      state: absent
    tags: 
      - section_2   

  - name: remove talk client (2.3.3)
    apt:
      name: talk
      state: absent
    tags: 
      - section_2     

  - name: remove telnet client (2.3.4)
    apt:
      name: telnet
      state: absent
    tags: 
      - section_2  

  - name: remove ldap client (2.3.5)
    apt:
      name: openldap-clients
      state: absent
    tags: 
      - section_2  

  - name: disabling ip forwarding (3.1.1)
    sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
      reload: true
      ignoreerrors: true
    tags: 
      - section_3  

  - name: set parameter in sysctl.conf (3.1.2)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'net.ipv4.conf.all.send_redirects = 0'
    tags: 
      - section_3    

  - name: set parameter in sysctl.conf (prt.2) (3.1.2)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'net.ipv4.conf.default.send_redirects = 0'
    tags: 
      - section_3          

  - name: set the active kernel parameter (prt.1) (3.1.2)
    shell: sysctl -w net.ipv4.conf.all.send_redirects=0
    tags: 
      - section_3

  - name: set the active kernel parameter (prt.2) (3.1.2)
    shell: sysctl -w net.ipv4.conf.default.send_redirects=0
    tags: 
      - section_3 

  - name: set the active kernel parameter (prt.2) (3.1.2)
    shell: sysctl -w net.ipv4.route.flush=1 
    tags: 
      - section_3  
    
  - name: disable the system from accepting source routed packets (3.2.1)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    tags: 
      - section_3    

  - name: disable ICMP redirects (3.2.2)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    tags: 
      - section_3   

  - name: disable secure ICMP redirects (3.2.2)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
    tags: 
      - section_3              

  - name: enable suspicious packets are logged (3.3.3)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 } 
    tags: 
      - section_3            