---
- name: Playbook for customize Debian9 by CIS
  hosts: all
  become: yes

  tasks: 

  - name: Copy config file for unneeded filesystems
    copy: 
      src: ./unneededfilesystem.conf
      dest: /etc/modprobe.d/ 
      mode: 777

  - name: Ensure mounting of unneeded filesystems
    command: rmmod unneededfilesystem

  - name: Remove freevxfs module
    modprobe: 
      name: freevxfs
      state: absent

  - name: Remove jffs2 module
    modprobe: 
      name: jffs2
      state: absent

  - name: Remove hfs module
    modprobe: 
      name: hfs
      state: absent

  - name: Remove hfsplus module
    modprobe: 
      name: hfsplus
      state: absent
      
  - name: Remove udf module  
    modprobe: 
      name: udf
      state: absent    
  
  - name: Ensure /tmp is configurated
    shell: mount | grep /tmp

  - name: Ensure separate partition exist for /var/tmp
    shell: mount | grep /var/tmp  
      
  - name: nodev,nosuid,noexec option for /var/tmp
    lineinfile:
      dest: /etc/fstab
      regexp: '/var/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-var/tmp /var/tmp ext4 nodev,nosuid,noexec 0 2'  
  
  - name: nodev option for /home
    lineinfile:
      dest: /etc/fstab
      regexp: '/home'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-home /home ext4 nodev 0 2'

  - name: nodev,nosuid,noexec option for /tmp
    lineinfile:
      dest: /etc/fstab
      regexp: '/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-tmp /tmp ext4 nodev,nosuid,noexec 0 2'

