---
- name: Playbook for customize Debian9 by CIS
  hosts: all
  become: yes

  tasks: 

  - name: Copy config file for unneeded filesystems
    copy: 
      src: ./unneededfilesystem.conf
      dest: /etc/modprobe.d/ 
      mode: 777

  - name: Ensure mounting of unneeded filesystems
    command: rmmod unneededfilesystem
