---
- name: Playbook for customize Debian9 by CIS
  hosts: all
  become: yes

  tasks: 

  - name: Copy config file for unneeded filesystems (1.1.1.1-1.1.1.5)
    copy: 
      src: ./unneededfilesystem.conf
      dest: /etc/modprobe.d/ 
      mode: 777
    tags: 
      - section_1  

  - name: Ensure mounting of unneeded filesystems (1.1.1.1-1.1.1.5)
    command: rmmod unneededfilesystem
    tags: 
      - section_1

  - name: Remove freevxfs module (1.1.1.1)
    modprobe: 
      name: freevxfs
      state: absent
    tags: 
      - section_1  

  - name: Remove jffs2 module (1.1.1.2)
    modprobe: 
      name: jffs2
      state: absent
    tags: 
      - section_1  

  - name: Remove hfs module (1.1.1.3)
    modprobe: 
      name: hfs
      state: absent
    tags: 
      - section_1  

  - name: Remove hfsplus module (1.1.1.4)
    modprobe: 
      name: hfsplus
      state: absent
    tags: 
      - section_1  
      
  - name: Remove udf module (1.1.1.5)
    modprobe: 
      name: udf
      state: absent    
    tags: 
      - section_1  
  
  - name: Ensure /tmp is configurated (1.1.2, 1.1.6)
    shell: mount | grep /tmp
    tags: 
      - section_1

  - name: nodev,nosuid,noexec option for /tmp (1.1.3-1.1.5)
    lineinfile:
      dest: /etc/fstab
      regexp: '/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-tmp /tmp ext4 nodev,nosuid,noexec 0 2'
    tags: 
      - section_1  

  - name: Ensure separate partition exist for /var/tmp (1.1.7)
    shell: mount | grep /var/tmp  
    tags: 
      - section_1
      
  - name: nodev,nosuid,noexec option for /var/tmp (1.1.8-1.1.10)
    lineinfile:
      dest: /etc/fstab
      regexp: '/var/tmp'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-var/tmp /var/tmp ext4 nodev,nosuid,noexec 0 2'  
    tags: 
      - section_1  
 
  - name: Ensure separate partition exist for /var/log (1.1.11)
    shell: mount | grep /var/log 
    tags: 
      - section_1

  - name: Ensure separate partition exist for /var/log/audit (1.1.12)
    shell: mount | grep /var/log/audit  
    tags: 
      - section_1

  - name: Ensure separate partition exist for /home (1.1.13)
    shell: mount | grep /home 
    tags: 
      - section_1     

  - name: nodev option for /home (1.1.14)
    lineinfile:
      dest: /etc/fstab
      regexp: '/home'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-home /home ext4 nodev 0 2'
    tags: 
      - section_1  

  - name: nodev,nosuid,noexec option for /dev/shm (1.1.15-1.1.17)
    lineinfile:
      dest: /etc/fstab
      regexp: '/dev/shm'
      insertbefore: 'defaults'
      line: '/dev/mapper/debian--vg-dev/shm /dev/shm ext4 nodev,nosuid,noexec 0 2'
    tags: 
      - section_1  

  - name: sticky bit for /var (1.1.21)
    shell: chmod -R +t /var
    tags: 
      - section_1

  - name: sticky bit for /home (1.1.21)
    shell: chmod -R +t /home
    tags: 
      - section_1

  - name: sticky bit for /tmp (1.1.21)
    shell: chmod -R +t /tmp
    tags: 
      - section_1

  - name: noauto option for cd/dvd (1.1.22)
    lineinfile:
      dest: /etc/fstab
      regexp: '/cdrom0'
      insertbefore: 'defaults'
      line: '/dev/sr0 /media/cdrom0 udf,iso9660 user,noauto 0 0'
    tags: 
      - section_1

 # - name: install aide (1.3.1)
 #   apt: 
 #     name: aide

 # - name: create regulary checking filesystem job (1.3.2)
 #   cron:
 #     name: 'regulary checking filesystem'
 #     minute: '0'
 #     hour: '5'
 #     job: /usr/bin/aide.wrapper 

  - name: confin premitions bootloader prt.1 (1.4.1)
    shell: chown root:root /boot/grub/grub.cfg 
    tags: 
      - section_1  

  - name: confin premitions bootloader prt.2 (1.4.1)
    shell: chmod og-rwx /boot/grub/grub.cfg 
    tags: 
      - section_1     

  - name: added line in limits.conf (1.5.1)
    lineinfile: 
      dest: '/etc/security/limits.conf'
      regexp: ''
      insertbefore: EOF
      line: '* hard core 0'
    tags: 
      - section_1  

  - name: set parameter in sysctl.conf (1.5.1)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'fs.suid_dumpable = 0'  
      tags: 
      - section_1   

  - name: run command to the activate kernel parameter (1.5.1)
    shell: sysctl -w fs.suid_dumpable=0
    tags: 
      - section_1

  - name: set parameter in sysctl.conf (1.5.2)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'kernel.randomize_va_space = 2' 
    tags: 
      - section_1      

  - name: run command to the activate kernel parameter (1.5.2)
    shell: sysctl -w kernel.randomize_va_space=2
    tags: 
      - section_1

  - name: restore binaries (1.5.4)
    shell: prelink -ua
    tags: 
      - section_1

  - name: remove prelink (1.5.4)
    apt:
      name: prelink
      state: absent
    tags: 
      - section_1  

  - name: checking /etc/motd file (1.7.1.1)
    shell: cat /etc/motd
    tags: 
      - section_1

  - name: configuration local login banner (1.7.1.2)
    lineinfile:
      dest: /etc/issue
      regexp: '*Debian*'
      insertbefore: BOF
      line: 'Authorized uses only. All activity may be monitored and reported.'
    tags: 
      - section_1  

  - name: configuration remote login banner (1.7.1.3)
    lineinfile:
      dest: /etc/issue.net
      regexp: '*Debian*'
      insertbefore: BOF
      line: 'Authorized uses only. All activity may be monitored and reported.'
    tags: 
      - section_1  

  - name: change ownership for /etc/motd (1.7.1.4)
    shell: chown root:root /etc/motd
    tags: 
      - section_1

  - name: change premissions for /etc/motd (1.7.1.4)
    shell: chmod 644 /etc/motd
    tags: 
      - section_1

  - name: change ownership for /etc/issue (1.7.1.5)
    shell: chown root:root /etc/issue
    tags: 
      - section_1

  - name: change premissions for /etc/issue (1.7.1.5)
    shell: chmod 644 /etc/issue
    tags: 
      - section_1

  - name: change ownership for /etc/issue.net (1.7.1.6)
    shell: chown root:root /etc/issue.net
    tags: 
      - section_1

  - name: change premissions for /etc/issue.net (1.7.1.6)
    shell: chmod 644 /etc/issue.net
    tags: 
      - section_1

  - name: edit greeter.dconf-defaults (1.7.2)
    lineinfile:
      dest: /etc/gdm3/greeter.dconf-defaults
      regexp: 'banner-message'
      insertbefore: BOF
      line: 'banner-message-enable=true'
    tags: 
      - section_1  

  - name: edit greeter.dconf-defaults prt.2 (1.7.2)
    lineinfile:
      dest: /etc/gdm3/greeter.dconf-defaults
      regexp: ''
      insertbefore: EOF
      line: 'Authorized uses only. All activity may be monitored and reported.'
    tags: 
      - section_1  

  - name: remove xinetd (2.1.1)
    apt:
      name: xinetd
      state: absent 
      purge: yes
    tags: 
      - section_2  

  - name: remove xinetd (2.1.2)
    apt:
      name: openbsd-inetd
      state: absent
    tags: 
      - section_2  

  - name: remove xserver-xorg* (2.2.2)
    apt:
      name: xserver-xorg*
      state: absent
    tags: 
      - section_2                        

  - name: disabled cups (2.2.4)     
    shell: systemctl disable cups
    tags: 
      - section_2

  - name: disabled DHCP (2.2.5)     
    shell: systemctl disable isc-dhcp-server
    tags: 
      - section_2

  - name: disabled DHCP (v6) (2.2.5)     
    shell: systemctl disable isc-dhcp-server6
    tags: 
      - section_2        

  - name: disabled ldap (2.2.6)     
    shell: systemctl disable slapd 
    tags: 
      - section_2 

  - name: disabled nfs (2.2.7)     
    shell: systemctl disable nfs-server
    tags: 
      - section_2

  - name: disabled rpc (2.2.7)     
    shell: systemctl disable rpcbind
    tags: 
      - section_2

  - name: disabled dns server (2.2.8)     
    shell: systemctl disable bind9
    tags: 
      - section_2

  - name: disabled ftp server (2.2.9)     
    shell: systemctl disable vsftpd
    tags: 
      - section_2

  - name: disabled http server (2.2.10)     
    shell: systemctl disable apache2
    tags: 
      - section_2

  - name: disabled samba (2.2.12)     
    shell: systemctl disable smbd
    tags: 
      - section_2

  - name: disabled http proxy server (2.2.13)     
    shell: systemctl disable squid
    tags: 
      - section_2

  - name: disabled snmp server (2.2.14)     
    shell: systemctl disable snmpd
    tags: 
      - section_2

  - name: disabled rsync (2.2.16)     
    shell: systemctl disable rsync
    tags: 
      - section_2 

  - name: disabled NIS (2.2.17)     
    shell: systemctl disable nis
    tags: 
      - section_2  

  - name: remove NIS client (2.3.1)
    apt:
      name: ypbind
      state: absent
    tags: 
      - section_2   

  - name: remove rsh client (2.3.2)
    apt:
      name: rsh
      state: absent
    tags: 
      - section_2   

  - name: remove talk client (2.3.3)
    apt:
      name: talk
      state: absent
    tags: 
      - section_2     

  - name: remove telnet client (2.3.4)
    apt:
      name: telnet
      state: absent
    tags: 
      - section_2  

  - name: remove ldap client (2.3.5)
    apt:
      name: openldap-clients
      state: absent
    tags: 
      - section_2  

  - name: disabling ip forwarding (3.1.1)
    sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
      reload: true
      ignoreerrors: true
    tags: 
      - section_3  

  - name: set parameter in sysctl.conf (3.1.2)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'net.ipv4.conf.all.send_redirects = 0'
    tags: 
      - section_3    

  - name: set parameter in sysctl.conf (prt.2) (3.1.2)
    lineinfile: 
      dest: '/etc/sysctl.conf'
      regexp: ''
      insertbefore: EOF
      line: 'net.ipv4.conf.default.send_redirects = 0'
    tags: 
      - section_3          

  - name: set the active kernel parameter (prt.1) (3.1.2)
    shell: sysctl -w net.ipv4.conf.all.send_redirects=0
    tags: 
      - section_3

  - name: set the active kernel parameter (prt.2) (3.1.2)
    shell: sysctl -w net.ipv4.conf.default.send_redirects=0
    tags: 
      - section_3 

  - name: set the active kernel parameter (prt.2) (3.1.2)
    shell: sysctl -w net.ipv4.route.flush=1 
    tags: 
      - section_3  
    
  - name: disable the system from accepting source routed packets (3.2.1)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    tags: 
      - section_3    

  - name: disable ICMP redirects (3.2.2)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    tags: 
      - section_3   

  - name: disable secure ICMP redirects (3.2.3)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
    tags: 
      - section_3              

  - name: enable suspicious packets are logged (3.2.4)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 } 
    tags: 
      - section_3            

  - name: disable broadcast ICMP requests (3.2.5)
    sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
      reload: true
      ignoreerrors: true   
    tags:
      - section_3 

  - name: ignore ICMP responses (3.2.6)
    sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
      reload: true
      ignoreerrors: true   
    tags:
      - section_3    

  - name: enable reverse path filtering (3.2.7)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv4.conf.all.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    tags:
      - section_3
      
  - name: enable tcp syn cookies (3.2.8)
    sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: true
      ignoreerrors: true  
    tags:
      - section_3      

  - name: install TCP wrappers (3.3.1)
    apt:
      name: tcpd
      state: present
    tags: 
      - section_3 

  - name: change ownership for /etc/hosts.allow (3.3.4)
    shell: chown root:root /etc/hosts.allow
    tags: 
      - section_3

  - name: change premissions for /etc/hosts.allow (3.3.4)
    shell: chmod 644 /etc/hosts.allow
    tags: 
      - section_3     

  - name: change ownership for /etc/hosts.deny (3.3.5)
    shell: chown root:root /etc/hosts.deny
    tags: 
      - section_3

  - name: change premissions for /etc/hosts.deny (3.3.5)
    shell: chmod 644 /etc/hosts.deny
    tags: 
      - section_3 

  - name: drop policy (prt.1) (3.5.1.1) 
    shell: iptables -P INPUT DROP
    tags:
      - section_3

  - name: drop policy (prt.2) (3.5.1.1) 
    shell: iptables -P OUTPUT DROP
    tags:
      - section_3

  - name: drop policy (prt.3) (3.5.1.1) 
    shell: iptables -P FORWARD DROP
    tags:
      - section_3 

  - name: loopback traffic configuration (prt.1) (3.5.1.2) 
    shell: iptables -A INPUT -i lo -j ACCEPT
    tags:
      - section_3

  - name: loopback traffic configuration (prt.2) (3.5.1.2) 
    shell: iptables -A OUTPUT -o lo -j ACCEPT
    tags:
      - section_3

  - name: loopback traffic configuration (prt.3) (3.5.1.2) 
    shell: iptables -A INPUT -s 127.0.0.0/8 -j DROP
    tags:
      - section_3

  - name: configuration exist for all open ports (3.5.1.4) 
    shell: iptables -A INPUT -p <protocol> --dport <port> -m state --state NEW -j ACCEPT
    tags:
      - section_3  

  - name: disable ip v6 (3.7)
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
    with_items:
      - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
      - { name: net.ipv6.conf.default.disable_ipv6, value: 1 }
    tags: 
      - section_3 

  - name: install rsyslog (4.2.3)
    apt:
      name: rsyslog
      state: present
    tags: 
      - section_4 

  - name: install syslog-ng (4.2.3)
    apt:
      name: syslog-ng
      state: present
    tags: 
      - section_4                                                   

  - name: enable rsyslog (4.2.1.1) 
    shell: systemctl enable rsyslog
    tags:
      - section_4      

  - name: set parameter in rsyslog.conf (4.2.1.3)
    lineinfile: 
      dest: '/etc/rsyslog.conf'
      regexp: ''
      insertbefore: EOF
      line: '$FileCreateMode 0640'
    tags: 
      - section_4 

  - name: enable syslog-ng (4.2.2.1) 
    shell: update-rc.d syslog-ng enable
    tags:
      - section_4                 

  - name: set parameter syslog-ng.conf (4.2.2.3)
    lineinfile: 
      dest: '/etc/syslog-ng/syslog-ng.conf'
      regexp: ''
      insertbefore: EOF
      line: 'options { chain_hostnames(off); flush_lines(0); perm(0640); stats_freq(3600); threaded(yes); };'
    tags: 
      - section_4 

  - name: set premissions on all logfiles (4.2.4) 
    shell: chmod -R g-wx,o-rwx /var/log/*
    tags:
      - section_4

  - name: enable cron (5.1.1) 
    shell: systemctl enable cron
    tags:
      - section_5 

  - name: change ownership for /etc/crontab (5.1.2)
    shell: chown root:root /etc/crontab
    tags: 
      - section_5

  - name: change premissions for /etc/crontab (5.1.2)
    shell: chmod og-rwx /etc/crontab
    tags: 
      - section_5

  - name: change ownership for /etc/cron.hourly (5.1.3)
    shell: chown root:root /etc/cron.hourly
    tags: 
      - section_5

  - name: change premissions for /etc/cron.hourly (5.1.3)
    shell: chmod og-rwx /etc/cron.hourly
    tags: 
      - section_5      

