---
- name: Test connection to servers #название playbook
  hosts: all #на каких серверах
  become: yes #запускать под sudo

  tasks: #список действий

  - name: Ping my servers
    ping:

#ТАБУЛЯЦИЮ НЕ СТАВИТЬ - будут ошибки разметки
#запускать: ansible-playbook playbook_ping.yml (hosts.txt содержит адреса целевых серверов)

